2025-10-11  20:30:32.053 | info | qcxdz79geg559t | Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t | RuntimeError: Failed to import diffusers.pipelines.qwenimage.pipeline_qwenimage_edit because of the following error (look up to see its traceback):\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |     raise RuntimeError(\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 955, in _get_module\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 943, in __getattr__\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |     value = getattr(module, name)\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:30:32.053 | info | qcxdz79geg559t |     value = getattr(module, name)\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from diffusers import QwenImageEditPipeline\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/app/rp_handler.py", line 4, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | Traceback (most recent call last):\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | The above exception was the direct cause of the following exception:\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | ModuleNotFoundError: Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     raise ModuleNotFoundError(\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2320, in __getattr__\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from transformers import Qwen2_5_VLForConditionalGeneration, Qwen2Tokenizer, Qwen2VLProcessor\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 21, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 953, in _get_module\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | Traceback (most recent call last):\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | The above exception was the direct cause of the following exception:\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t | RuntimeError: operator torchvision::nms does not exist\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/torch/_library/fake_impl.py", line 50, in register\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     handle = entry.fake_impl.register(\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 219, in _register_fake\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     use_lib._register_fake(\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 1069, in register\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     def meta_nms(dets, scores, iou_threshold):\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 164, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 10, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from torchvision.transforms import InterpolationMode\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py", line 55, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from .image_utils import ChannelDimension, ImageInput, is_vision_available\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/processing_utils.py", line 37, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from .processing_utils import Unpack\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 28, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |     from ...modeling_layers import GradientCheckpointingLayer\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 39, in <module>\n
2025-10-11  20:30:32.052 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |     raise e\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | Traceback (most recent call last):\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | By pulling and using the container, you accept the terms and conditions of this license:\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | This container image and its contents are governed by the NVIDIA Deep Learning Container License.\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | CUDA Version 12.1.1\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | \n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | ==========\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | == CUDA ==\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | ==========\n
2025-10-11  20:30:32.051 | info | qcxdz79geg559t | \n
2025-10-11  20:30:24.139 | error | qcxdz79geg559t | worker exited with exit code 1
2025-10-11  20:30:07.743 | error | qcxdz79geg559t | worker exited with exit code 1
2025-10-11  20:26:44.384 | error | vr9vunrpj1rbmi | worker exited with exit code 1
2025-10-11  20:26:41.833 | error | lqtnp3eib8itdc | worker exited with exit code 1
2025-10-11  20:26:38.984 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:26:27.263 | error | vr9vunrpj1rbmi | worker exited with exit code 1
2025-10-11  20:26:24.573 | error | lqtnp3eib8itdc | worker exited with exit code 1
2025-10-11  20:26:22.046 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:26:07.433 | error | lqtnp3eib8itdc | worker exited with exit code 1
2025-10-11  20:26:05.158 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:25:56.458 | error | x4hfoqq9f4tywt | worker exited with exit code 1
2025-10-11  20:25:50.314 | error | lqtnp3eib8itdc | worker exited with exit code 1
2025-10-11  20:25:48.340 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | RuntimeError: Failed to import diffusers.pipelines.qwenimage.pipeline_qwenimage_edit because of the following error (look up to see its traceback):\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     raise RuntimeError(\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 955, in _get_module\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 943, in __getattr__\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     value = getattr(module, name)\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     value = getattr(module, name)\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     from diffusers import QwenImageEditPipeline\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/app/rp_handler.py", line 4, in <module>\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | Traceback (most recent call last):\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | The above exception was the direct cause of the following exception:\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | ModuleNotFoundError: Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     raise ModuleNotFoundError(\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2320, in __getattr__\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     from transformers import Qwen2_5_VLForConditionalGeneration, Qwen2Tokenizer, Qwen2VLProcessor\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 21, in <module>\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 953, in _get_module\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | Traceback (most recent call last):\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | The above exception was the direct cause of the following exception:\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt | RuntimeError: operator torchvision::nms does not exist\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/torch/_library/fake_impl.py", line 50, in register\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     handle = entry.fake_impl.register(\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 219, in _register_fake\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |     use_lib._register_fake(\n
2025-10-11  20:25:46.344 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 1069, in register\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     def meta_nms(dets, scores, iou_threshold):\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 164, in <module>\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 10, in <module>\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     from torchvision.transforms import InterpolationMode\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py", line 55, in <module>\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     from .image_utils import ChannelDimension, ImageInput, is_vision_available\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/processing_utils.py", line 37, in <module>\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     from .processing_utils import Unpack\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 28, in <module>\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     from ...modeling_layers import GradientCheckpointingLayer\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 39, in <module>\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     raise e\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:25:46.343 | info | x4hfoqq9f4tywt |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__\n
2025-10-11  20:25:44.738 | info | x4hfoqq9f4tywt | Traceback (most recent call last):\n
2025-10-11  20:25:44.738 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:44.738 | info | x4hfoqq9f4tywt | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | By pulling and using the container, you accept the terms and conditions of this license:\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | This container image and its contents are governed by the NVIDIA Deep Learning Container License.\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | CUDA Version 12.1.1\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | ==========\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | == CUDA ==\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | ==========\n
2025-10-11  20:25:44.737 | info | x4hfoqq9f4tywt | \n
2025-10-11  20:25:39.201 | error | x4hfoqq9f4tywt | worker exited with exit code 1
2025-10-11  20:25:33.148 | error | lqtnp3eib8itdc | worker exited with exit code 1
2025-10-11  20:25:31.500 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:25:22.715 | error | x4hfoqq9f4tywt | worker exited with exit code 1
2025-10-11  20:25:15.988 | error | lqtnp3eib8itdc | worker exited with exit code 1
2025-10-11  20:25:14.682 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:25:06.323 | error | x4hfoqq9f4tywt | worker exited with exit code 1
2025-10-11  20:24:57.772 | error | yyocasiq7egdyf | worker exited with exit code 1
2025-10-11  20:24:49.815 | error | x4hfoqq9f4tywt | worker exited with exit code 1
2025-10-11  20:24:47.813 | error | xjzvzn92zi411x | worker exited with exit code 1
2025-10-11  20:24:33.292 | error | x4hfoqq9f4tywt | worker exited with exit code 1
2025-10-11  20:24:30.652 | error | xjzvzn92zi411x | worker exited with exit code 1
2025-10-11  20:24:27.075 | error | ia79hzlvcs4wor | worker exited with exit code 1
2025-10-11  20:24:13.397 | error | xjzvzn92zi411x | worker exited with exit code 1
2025-10-11  20:24:10.203 | error | ia79hzlvcs4wor | worker exited with exit code 1
2025-10-11  20:23:56.168 | error | xjzvzn92zi411x | worker exited with exit code 1
2025-10-11  20:23:53.304 | error | ia79hzlvcs4wor | worker exited with exit code 1
2025-10-11  20:23:50.214 | error | n41xwd9aoy8hs7 | worker exited with exit code 1
2025-10-11  20:23:38.894 | error | xjzvzn92zi411x | worker exited with exit code 1
2025-10-11  20:23:36.310 | error | ia79hzlvcs4wor | worker exited with exit code 1
2025-10-11  20:23:33.969 | error | n41xwd9aoy8hs7 | worker exited with exit code 1
2025-10-11  20:23:21.697 | error | xjzvzn92zi411x | worker exited with exit code 1
2025-10-11  20:23:19.393 | error | ia79hzlvcs4wor | worker exited with exit code 1
2025-10-11  20:23:17.740 | error | n41xwd9aoy8hs7 | worker exited with exit code 1
2025-10-11  20:23:02.436 | error | ia79hzlvcs4wor | worker exited with exit code 1
2025-10-11  20:23:01.498 | error | n41xwd9aoy8hs7 | worker exited with exit code 1
2025-10-11  20:22:45.259 | error | n41xwd9aoy8hs7 | worker exited with exit code 1
2025-10-11  20:22:28.992 | error | n41xwd9aoy8hs7 | worker exited with exit code 1
2025-10-11  20:22:25.713 | info | n41xwd9aoy8hs7 | Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:22:25.713 | info | n41xwd9aoy8hs7 | RuntimeError: Failed to import diffusers.pipelines.qwenimage.pipeline_qwenimage_edit because of the following error (look up to see its traceback):\n
2025-10-11  20:22:25.713 | info | n41xwd9aoy8hs7 |     raise RuntimeError(\n
2025-10-11  20:22:25.713 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 955, in _get_module\n
2025-10-11  20:22:25.713 | info | n41xwd9aoy8hs7 |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:22:25.713 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 943, in __getattr__\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     value = getattr(module, name)\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     value = getattr(module, name)\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from diffusers import QwenImageEditPipeline\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/app/rp_handler.py", line 4, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | Traceback (most recent call last):\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | The above exception was the direct cause of the following exception:\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | ModuleNotFoundError: Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     raise ModuleNotFoundError(\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2320, in __getattr__\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from transformers import Qwen2_5_VLForConditionalGeneration, Qwen2Tokenizer, Qwen2VLProcessor\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 21, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 953, in _get_module\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | Traceback (most recent call last):\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | The above exception was the direct cause of the following exception:\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 | RuntimeError: operator torchvision::nms does not exist\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/torch/_library/fake_impl.py", line 50, in register\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     handle = entry.fake_impl.register(\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 219, in _register_fake\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     use_lib._register_fake(\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 1069, in register\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     def meta_nms(dets, scores, iou_threshold):\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 164, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 10, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from torchvision.transforms import InterpolationMode\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py", line 55, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from .image_utils import ChannelDimension, ImageInput, is_vision_available\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/processing_utils.py", line 37, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from .processing_utils import Unpack\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 28, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |     from ...modeling_layers import GradientCheckpointingLayer\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 39, in <module>\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:22:25.712 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |     raise e\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:22:25.711 | info | n41xwd9aoy8hs7 |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | Traceback (most recent call last):\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | By pulling and using the container, you accept the terms and conditions of this license:\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | This container image and its contents are governed by the NVIDIA Deep Learning Container License.\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | CUDA Version 12.1.1\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | ==========\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | == CUDA ==\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | ==========\n
2025-10-11  20:22:25.094 | info | n41xwd9aoy8hs7 | \n
2025-10-11  20:22:24.492 | error | p8pdn3ajq857kz | worker exited with exit code 1
2025-10-11  20:22:08.994 | error | w7bpughils1tbx | worker exited with exit code 1
2025-10-11  20:22:08.077 | error | p8pdn3ajq857kz | worker exited with exit code 1
2025-10-11  20:21:55.502 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:21:52.081 | error | w7bpughils1tbx | worker exited with exit code 1
2025-10-11  20:21:51.648 | error | p8pdn3ajq857kz | worker exited with exit code 1
2025-10-11  20:21:38.846 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:21:35.272 | error | p8pdn3ajq857kz | worker exited with exit code 1
2025-10-11  20:21:22.192 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:21:05.589 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:20:50.208 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:20:49.857 | error | i43onzn8vgr3ti | worker exited with exit code 1
2025-10-11  20:20:48.937 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:20:33.949 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:20:33.004 | error | i43onzn8vgr3ti | worker exited with exit code 1
2025-10-11  20:20:32.253 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:20:17.689 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:20:16.129 | error | i43onzn8vgr3ti | worker exited with exit code 1
2025-10-11  20:20:15.665 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | RuntimeError: Failed to import diffusers.pipelines.qwenimage.pipeline_qwenimage_edit because of the following error (look up to see its traceback):\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |     raise RuntimeError(\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 955, in _get_module\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 943, in __getattr__\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |     value = getattr(module, name)\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |     value = getattr(module, name)\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 944, in __getattr__\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |     from diffusers import QwenImageEditPipeline\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |   File "/app/rp_handler.py", line 4, in <module>\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | Traceback (most recent call last):\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | The above exception was the direct cause of the following exception:\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz | ModuleNotFoundError: Could not import module 'Qwen2_5_VLForConditionalGeneration'. Are this object's requirements defined correctly?\n
2025-10-11  20:20:04.467 | info | j0c81xuw4ixkdz |     raise ModuleNotFoundError(\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2320, in __getattr__\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     from transformers import Qwen2_5_VLForConditionalGeneration, Qwen2Tokenizer, Qwen2VLProcessor\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/qwenimage/pipeline_qwenimage_edit.py", line 21, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py", line 953, in _get_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz | Traceback (most recent call last):\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz | The above exception was the direct cause of the following exception:\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz | RuntimeError: operator torchvision::nms does not exist\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/torch/_library/fake_impl.py", line 50, in register\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     handle = entry.fake_impl.register(\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 219, in _register_fake\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     use_lib._register_fake(\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/torch/library.py", line 1069, in register\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     def meta_nms(dets, scores, iou_threshold):\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/torchvision/_meta_registrations.py", line 164, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/torchvision/__init__.py", line 10, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     from torchvision.transforms import InterpolationMode\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py", line 55, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     from .image_utils import ChannelDimension, ImageInput, is_vision_available\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/processing_utils.py", line 37, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     from .processing_utils import Unpack\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 28, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     from ...modeling_layers import GradientCheckpointingLayer\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py", line 39, in <module>\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     return _bootstrap._gcd_import(name[level:], package, level)\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     return importlib.import_module("." + module_name, self.__name__)\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2345, in _get_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     raise e\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2347, in _get_module\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |     module = self._get_module(self._class_to_module[name])\n
2025-10-11  20:20:04.466 | info | j0c81xuw4ixkdz |   File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 2317, in __getattr__\n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | Traceback (most recent call last):\n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.\n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license\n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | By pulling and using the container, you accept the terms and conditions of this license:\n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | This container image and its contents are governed by the NVIDIA Deep Learning Container License.\n
2025-10-11  20:20:03.791 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | CUDA Version 12.1.1\n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | ==========\n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | == CUDA ==\n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | ==========\n
2025-10-11  20:20:03.790 | info | j0c81xuw4ixkdz | \n
2025-10-11  20:20:01.411 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:19:59.306 | error | i43onzn8vgr3ti | worker exited with exit code 1
2025-10-11  20:19:58.033 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:19:45.119 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:19:42.454 | error | i43onzn8vgr3ti | worker exited with exit code 1
2025-10-11  20:19:42.119 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:19:28.826 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:19:25.477 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:19:12.515 | error | mjz8xf1y4cwog1 | worker exited with exit code 1
2025-10-11  20:19:08.734 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:18:52.068 | error | j0c81xuw4ixkdz | worker exited with exit code 1
2025-10-11  20:18:30.557 | error | yqvvo65l6t4ce6 | worker exited with exit code 1
2025-10-11  20:18:13.943 | error | yqvvo65l6t4ce6 | worker exited with exit code 1
2025-10-11  20:12:32.312 | error | ghetohra2jbadr | worker exited with exit code 1
2025-10-11  20:12:16.089 | error | ghetohra2jbadr | worker exited with exit code 1
2025-10-11  20:10:09.696 | error | bw96tb4yr95hr9 | worker exited with exit code 1
2025-10-11  20:08:53.785 | error | 6qeepene8n2bp3 | worker exited with exit code 1
2025-10-11  20:08:37.275 | error | 6qeepene8n2bp3 | worker exited with exit code 1
2025-10-11  20:08:20.778 | error | 6qeepene8n2bp3 | worker exited with exit code 1
2025-10-11  20:08:04.228 | error | 6qeepene8n2bp3 | worker exited with exit code 1
2025-10-11  20:05:39.116 | error | 0a8peztb41dob4 | worker exited with exit code 1
2025-10-11  20:05:23.073 | error | 0a8peztb41dob4 | worker exited with exit code 1
2025-10-11  20:05:06.942 | error | 0a8peztb41dob4 | worker exited with exit code 1
2025-10-11  20:04:50.915 | error | 0a8peztb41dob4 | worker exited with exit code 1
2025-10-11  20:04:34.931 | error | 0a8peztb41dob4 | worker exited with exit code 1
2025-10-11  20:04:18.929 | error | 0a8peztb41dob4 | worker exited with exit code 1
2025-10-11  20:00:29.820 | error | crcv4ob2r93d0x | worker exited with exit code 1
2025-10-11  20:00:12.971 | error | crcv4ob2r93d0x | worker exited with exit code 1
2025-10-11  19:59:55.991 | error | crcv4ob2r93d0x | worker exited with exit code 1
2025-10-11  19:59:39.001 | error | crcv4ob2r93d0x | worker exited with exit code 1
2025-10-11  19:58:42.072 | error | n89sgo0gy0ajrv | worker exited with exit code 1
2025-10-11  19:58:28.673 | error | 25eqjq7hfx27m1 | worker exited with exit code 1
2025-10-11  19:58:22.998 | error | n89sgo0gy0ajrv | worker exited with exit code 1
2025-10-11  19:58:12.358 | error | 25eqjq7hfx27m1 | worker exited with exit code 1
2025-10-11  19:58:11.820 | error | n89sgo0gy0ajrv | worker exited with exit code 1
2025-10-11  19:54:19.108 | error | xi1shierfu8rhz | worker exited with exit code 1
2025-10-11  19:54:02.187 | error | xi1shierfu8rhz | worker exited with exit code 1
2025-10-11  19:53:45.326 | error | xi1shierfu8rhz | worker exited with exit code 1
2025-10-11  19:53:28.503 | error | xi1shierfu8rhz | worker exited with exit code 1
2025-10-11  19:53:11.673 | error | xi1shierfu8rhz | worker exited with exit code 1
2025-10-11  19:52:54.802 | error | xi1shierfu8rhz | worker exited with exit code 1